# The base hadoop image to use for all components.
# See this repo for image build details: https://github.com/chenseanxy/helm-hbase-chart/tree/master/image

# hbaseImage: chenseanxy/hbase:1.4.10-hadoop3.1.2
hbaseImage: 192.168.10.223:5000/hbase:1.2.4
imagePullPolicy: "IfNotPresent"

# Select anitAffinity as either hard or soft, default is hard
# antiAffinity: "soft"

hbase:
  hmaster:
    replicas: 2
    pdbMinAvailable: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
  regionServer:
    replicas: 3
    pdbMinAvailable: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"
  hdfs: 
    rootidr: "hdfs://hdfs-namenode-0.hdfs-namenode.saida.svc.cluster.local:8020/hbase"
    name: "hdfs"
    port: "8020"


persistence:
  nameNode:
    enabled: false
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 50Gi

  dataNode:
    enabled: false
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 200Gi


zookeeper:
  zookeeperQuorumOverride: ""
  name: "hdfs-zookeeper"
  quorumSize: 3
